### ISSUE TITLE
Success modals: display icon correctly

### ISSUE THREAD

**Issue by HirdayGupta** [TEAMMATES/teammates#7708]
Found this while working on #5979 

**The problem:**
When used with the SUCCESS color, the bootbox modal's heading does not seem to look correct. The header text is on the next line to the success icon. It should either be on the same line as it, or the icon should not appear (only for modals, not for regular status messages) altogether.

This is what it looks like:
<img width="631" alt="screen shot 2017-07-09 at 3 14 16 am" src="https://user-images.githubusercontent.com/18088721/27989446-91860ada-6456-11e7-8e31-7c6b939b144c.png">

**Why it went unnoticed?**
We don't use success modals anywhere in the system (as per my search, at least).

**The Cause:**
PR #7067's solution to Issue #7058. This added the tick icon to all Success Messages indiscriminately using the CSS `:before()` selector.

**Possible Solutions**
- Avoiding adding the tick mark icon when in a `modal-header` context (possibly through CSS).
- Figuring out why the modal header appears below the icon and fixing it.

**Comment by HirdayGupta** [comment]
Just realised that the first of the suggested solutions has an easy implementation using the CSS `:not()` selector. Should I go ahead with this?

**Comment by HirdayGupta** [comment]
@damithc should I go ahead with the approach I described in the previous comment? Or is it essential that the icon is displayed in the modal header as well?

**Comment by damithc** [comment]
> @damithc should I go ahead with the approach I described in the previous comment? Or is it essential that the icon is displayed in the modal header as well?

@chowyb @whipermr5 what do you think?

**Comment by LiHaoTan** [comment]
While waiting for them to reply, I have some input.

The original approach of showing modal dialogs (even before adding icons to alerts) probably was not ideal. It made use of the `alert-*` class and yet the function named the styling as colors when it is really doing a whole lot more. If we wanted to style only colors, we should use `bg-*` and `text-*`.

This is why we may notice some differences as compared to using `alert-*` since it does more than that.

Take for example `alert-success`, it is styled as follows:
```less
.alert-success {
  .alert-variant(@alert-success-bg; @alert-success-border; @alert-success-text);
}

.alert-variant(@background; @border; @text-color) {
  background-color: @background;
  border-color: @border;
  color: @text-color;

  hr {
    border-top-color: darken(@border, 5%);
  }
  .alert-link {
    color: darken(@text-color, 10%);
  }
}
```

Setting `border-color` requires a border, and in this case, `modal-header` happened to nicely define nicely `border-bottom`, so `border-color` from `alert-*` will override the color. If `modal-header` did not define `border-bottom`, `border-color` would have done nothing.

So **it luckily just happened to work well**.  Therefore if we really wanted the exact behavior of `alert-*` we should have our own style for the `modal` itself, not using `alert`, since it can be changed in ways we may not expect.

As for the issue here on hand,

In this case, the problem here is because the header uses a `h4` tag, which is a block element, and thus automatically is started on a new line.

`float: left` can solve this problem, or we can make use of the pseudo `before` on the `h4`. I honestly don't know which is preferable but I think `not` is not the right approach.
