### ISSUE TITLE
`teammatesCommon.css`: Remove `cursor: hand;`

### ISSUE THREAD

**Issue by LiHaoTan** [TEAMMATES/teammates#7880]
Replace

```css
.cursor-pointer {
    cursor: pointer;
    cursor: hand;
}
```
with
```css
.cursor-pointer {
    cursor: pointer;
}
```

---
> In the past the hand value was Microsoft's way of saying pointer; and IE 5.0 and 5.5 only support hand. Because it's the cursor value that's used most often, most other browsers have also implemented hand.

> Since IE 6 and 7 support pointer, there's no more reason to use hand, except when older IEs are part of your target audience. 

https://quirksmode.org/css/user-interface/cursor.html#note

The support for `hand` value has been dropped since IE9 as well.
