### ISSUE TITLE
Add custom gradle task for deployment

### ISSUE THREAD

**Issue by tshradheya** [TEAMMATES/teammates#8260]
Edit by @whipermr5: Write a custom gradle task that encompasses `./gradlew appengineDeploy appengineDeployCron appengineDeployIndex appengineDeployQueue` and update the instructions in `development.md`.

<hr>

When trying to log in as instructor in my app teammates-shradheya.appspot.com

I am getting the following error after I add an instructor and attempt to join as instructor using the unique link mentioned in the email sent and then logging in using the google account( Note: I have used a different Google account than the one i used to set up the GCP, it is the account on which I got the email of the instructor joining link)

![34327113-58d42152-e8e2-11e7-9f9d-02a080cdb04b](https://user-images.githubusercontent.com/12574756/34354204-c56b51da-ea3d-11e7-8a22-15035fef1e6d.png)

I am not sure what could be the reason as to why I am not able to access the instructor page.

**Comment by damithc** [comment]
If you have multiple Google accounts, you should logout from all except the one you want to use for the instructor. 
Note that you can go to  https://console.cloud.google.com to check the logs.

**Comment by tshradheya** [comment]
I tried logging out and using only the necessary account but it still showed me the error webpage.

On looking up the logs, I found the following:

`com.google.appengine.api.datastore.DatastoreNeedIndexException: no matching index found. recommended index is: - kind: Instructor properties: - name: googleId - name: isArchived The suggested index for this query is: <datastore-index kind="Instructor" ancestor="false" source="manual"> <property name="googleId" direction="asc"/> <property name="isArchived" direction="asc"/> </datastore-index>
at teammates.storage.api.EntitiesDb.makeAttributes (EntitiesDb.java:300)
at teammates.storage.api.InstructorsDb.getInstructorsForGoogleId (InstructorsDb.java:186)
at teammates.logic.core.InstructorsLogic.getInstructorsForGoogleId (InstructorsLogic.java:134)
at teammates.logic.core.CoursesLogic.getCoursesSummaryWithoutStatsForInstructor (CoursesLogic.java:587)
at teammates.logic.api.Logic.getCourseSummariesWithoutStatsForInstructor (Logic.java:583)
at teammates.ui.controller.InstructorHomePageAction.loadPage (InstructorHomePageAction.java:52)
at teammates.ui.controller.InstructorHomePageAction.execute (InstructorHomePageAction.java:31)
... `

This is the error which happened on multiple occurences of me trying out using different accounts. Not able to understand what could the issue be.

**Comment by LiHaoTan** [comment]
@tshradheya I suspect you did not deploy the datastore indexes. It seems our instructions might be a little lacking.

**Comment by tshradheya** [comment]
Can you give more instructions as to how to deploy datastore indexes?

**Comment by damithc** [comment]
It used to be the case that xml files describing the indexes are auto-created by the dev server.  What I used to do was to run the full test suite against the dev server which auto-generates all indexes needed by functionalities covered by the test cases. After that, deploying to the staging server ensures that the index files are also replicated in the dev server. You can give that a try.

**Comment by wkurniawan07** [comment]
I might know what's going on, but I need to confirm something first. @tshradheya can you go to your app engine debug console (URL should be `https://console.cloud.google.com/debug?project=teammates-shradheya`), and tell me what are the files contained in the `app-engine:/WEB-INF/appengine-generated` folder?

**Comment by tshradheya** [comment]
The following are the files in /app-generated

- app.yaml
- cron.yaml
- index.yaml
- queue.yaml

The following is the data inside the `index.yaml` file

```
indexes:
- kind: "Instructor"
  properties:
  - name: "googleId"
    direction: asc
  - name: "isArchived"
    direction: asc
- kind: "AdminEmail"
  properties:
  - name: "isInTrashBin"
    direction: asc
  - name: "sendDate"
    direction: asc
- kind: "FeedbackSession"
  properties:
  - name: "isClosingEmailEnabled"
    direction: asc
  - name: "sentClosedEmail"
    direction: asc
  - name: "endTime"
    direction: asc
- kind: "FeedbackSession"
  properties:
  - name: "isClosingEmailEnabled"
    direction: asc
  - name: "sentClosingEmail"
    direction: asc
  - name: "endTime"
    direction: asc
- kind: "FeedbackSession"
  properties:
  - name: "sentOpenEmail"
    direction: asc
  - name: "startTime"
    direction: asc
- kind: "FeedbackSession"
  properties:
  - name: "isPublishedEmailEnabled"
    direction: asc
  - name: "sentPublishedEmail"
    direction: asc
  - name: "feedbackSessionType"
    direction: asc

```
